### ISSUE TITLE
Launcher clearer selection feedback

### ISSUE THREAD

**Issue by jonclothcat** [ynput/ayon-launcher#109]
In the Launcher, when clicking on a task and moving over the software icon, it's not clear that it's either changing colour (there's a subtle change in text colour) or is available to select. It needs a clearer box when you're over it and a 'press' state when clicked. (This is an issue common to the Publisher, where a 'Repair' button gets clicked but there's no feedback to show that something is happening or the command has worked.)

Also, in the Launcher, all the tasks are available, regardless of whether they've been started or has even got a scene file associated with it. E.g. there could already be an animation task but the scene is still in layout. There's no indication of what stage the scene is currently at, what the most recent task saved was, and how many versions are available.

- Clearer hover and press state over applications in launcher
- Filter tasks based on whether they have been started or not
- Add status indications to launcher.

**Comment by iLLiCiTiT** [comment]
This is issue for launcher tool in `ayon-core`. This is AYON launcher a.k.a. desktop application. Please move the issue to ayon-core repository.
