### ISSUE TITLE
Many problems on MacOS (arm)

### ISSUE THREAD

**Issue by apvlv** [ynput/ayon-launcher#113]
Hello, 

thank you for this software, which looks very comprehensive and promising, since you are going forward to migrate OpenPype. I understand that the priority is to support paying customers/studios, but is there a definitive guide how to install the open source version, e.g. for mac based artists? I've set up the server with the docker image and it works so far well. But i'm struggling to set up the launcher app on my m2 pro laptop. Firstly i had following error messages in the console:

`Couldn't find OpenImageIO source file for platform 'Darwin'`

Indeed there are no files for darwin on the openpype distribution server. I then downloaded oiio binaries myself and put them into the third-party folder. Don't know if that was right though, but the error disappeared. 

But now I get the next error in the admin console:

`>>> [  SiteSync Started  ] 
Traceback (most recent call last):
  File "/Users/andrej/Library/Application Support/AYON/addons/core_0.3.1/ayon_core/tools/launcher/ui/actions_widget.py", line 362, in _on_model_refresh
    self._view.update()
TypeError: QListView.update() takes exactly one argument (0 given)`

So my question is: have I missed something in the documentation, is the app functioning at all when installing from the dmg or are there some caveats to know about? The launcher works, but when I open a project, there is something not right, it is mostly completely empty. Also when I try to quit the launcher, it freezes, so I have to kill the process by myself.

Thank you very much!

**Comment by apvlv** [comment]
UPD: when I try to build ayon launcher for myself I get the following error:

`...
>>> Dependency cleanup done in 3.889408 secs.
Traceback (most recent call last):
  File "/Users/andrej/dev/ayon-launcher/tools/build_post_process.py", line 682, in <module>
    main()
  File "/Users/andrej/dev/ayon-launcher/tools/build_post_process.py", line 675, in main
    post_build_process(ayon_root, build_root)
  File "/Users/andrej/dev/ayon-launcher/tools/build_post_process.py", line 461, in post_build_process
    store_base_metadata(build_root, build_content_root, ayon_version)
  File "/Users/andrej/dev/ayon-launcher/tools/build_post_process.py", line 446, in store_base_metadata
    "runtime_python_modules": get_runtime_modules(build_content_root),
  File "/Users/andrej/dev/ayon-launcher/tools/build_post_process.py", line 352, in get_runtime_modules
    raise ValueError("Wasn't able to get runtime modules.")
ValueError: Wasn't able to get runtime modules.`

**Comment by iLLiCiTiT** [comment]
Hello, thanks for feedback. The issues are not directly related to AYON launcher, but let's get to it.

> Indeed there are no files for darwin on the openpype distribution server. I then downloaded oiio binaries myself and put them into the third-party folder. Don't know if that was right though, but the error disappeared.

That's related to third party addon. The addon does not contain oiio binaries. We're not aware of binary build that can be packaged and would work for all supported versions of macOs. If you know about one and you can provide it, we would be more than happy to add it by default.

> But now I get the next error in the admin console:
> >>> [  SiteSync Started  ]  Traceback (most recent call last): File "/Users/andrej/Library/Application Support/AYON/addons/core_0.3.1/ayon_core/tools/launcher/ui/actions_widget.py", line 362, in _on_model_refresh self._view.update() TypeError: QListView.update() takes exactly one argument (0 given)

This is more interesting. This is related to ayon-core addon. I think it is related to difference in PySide2 and PySide6, we can take a look.
Is this error somehow blocking? It should not cause huge harm.
