### ISSUE TITLE
Centos7 Build launcher not working after building deps

### ISSUE THREAD

**Issue by ddesmond** [ynput/ayon-launcher#138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

I am rebuilding localy the launcher from develop/main, on centos7 and it passes, i can then go and build deps with the dependencies tools and bundle it with create -b bundlename. 

After launching ayon fomr the folder we have Missing Ayon Core.

If I do bootstrap I get wrong deps for centos7 as rocky. Those in turn fail with many errors since its not the same platform.

### Expected Behavior:

Build and launch properly

### Version

1.0.0

### What platform you are running on?

Linux / Centos

### Steps To Reproduce:

Steps outlined in the repo guide.
./tools/make.sh create-env
./tools/make.sh install-runtime-dependencies
./tools/make.sh build
./tools/make.sh make-installer

then make.sh upload and passes to the server.
I can see the launcher version in my downloads on ayon page.

![image](https://github.com/user-attachments/assets/258ce345-e4fb-4591-bb65-4920da07e682)

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
The command line errors with:
>>> Connected to AYON server https://ayon.aaamaa.com
Extracting /home/user/.local/share/AYON/dependency_packages/ayon_2408031157_linux.zip/ayon_2408031157_linux.zip -> /home/user/.local/share/AYON/dependency_packages/ayon_2408031157_linux.zip
```

**Comment by iLLiCiTiT** [comment]
I'm not sure what to do with this issue? If the issue is wrong dependency package then we can't do much about it. Bootstrap contains rocky9 installer and dependency packages, to create dependency package please use https://github.com/ynput/ayon-dependencies-tool and make sure that is the one used in your bundle.

**Comment by ddesmond** [comment]
Ok, lets close this issue then, if its centos7 build related its going to history anyway.

thanks @iLLiCiTiT
