### ISSUE TITLE
Docker Centos7 outdated

### ISSUE THREAD

**Issue by ddesmond** [ynput/ayon-launcher#139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

The centos7 docker file is outdated.
https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm does not exists anymore
deltarpm errors aswell.
The rest is broken and i didint try to recover it, just raising this up

### Expected Behavior:

build docker centos7 should work, its outdated and broken.

### Version

1.0.0

### What platform you are running on?

Linux / Centos

### Steps To Reproduce:

build docker for centos7

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by iLLiCiTiT** [comment]
We were unable to build centos7 anymore, thus centos7 docker build was dropped https://github.com/ynput/ayon-launcher/pull/145 .
